# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63ee1e8bc61dd6fd41c41ef7d7631673f2840b382b0fcf1762cacc6c87b49c294b3c5ca8c86f7cf4c10b6529fe2a0cfe438eaa4e54996154e604603e69493bb1

test:
  secret_key_base: a4286a09501dfed8e8b329e96a4703c8f86992dd841be3db9dbfe32214bf8af30012675964128248074e9f803bfccffbcbb382b1a326a7c74b3a5682853a2e07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
